version: 0.1
phases:
  install:
    commands:
      - pip3 install networkx
      - pip3 install pandas, numpy
  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Running tests"
      - cd tests ; pytest -v -s -W ignore::DeprecationWarning