version: 2
jobs:
  build:
    branches:
      ignore:
          - /feature*/
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      # - run:
          # command: |
          #   pip install networkx
          #   pip install pandas
          #   pip install numpy
      - run: ls .
      - run: echo "hello world"