version: 2
jobs:
  build:
    branches:
      ignore:
          - /feature*/
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install networkx
            pipenv install pandas
            pipenv install numpy
      - run: ls .
      # - run: pytest -v -s -W ignore::DeprecationWarning tests/